waarbot/config/routes.rb
Waarbot::Application.routes.draw do
  resources :targets

  resources :players

  resources :units

end

waarbot/app/models/unit.rb
class Unit < ActiveRecord::Base
end

waarbot/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.xml
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @units }
    end
  end

  # GET /units/1
  # GET /units/1.xml
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/new
  # GET /units/new.xml
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.xml
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to(@unit, :notice => 'Unit was successfully created.') }
        format.xml  { render :xml => @unit, :status => :created, :location => @unit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.xml
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to(@unit, :notice => 'Unit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.xml
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to(units_url) }
      format.xml  { head :ok }
    end
  end
end

waarbot/app/helpers/units_helper.rb
module UnitsHelper
end

waarbot/app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :attack %><br />
    <%= f.text_field :attack %>
  </div>
  <div class="field">
    <%= f.label :defense %><br />
    <%= f.text_field :defense %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

waarbot/app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

waarbot/app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Cost</th>
    <th>Attack</th>
    <th>Defense</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.code %></td>
    <td><%= unit.name %></td>
    <td><%= unit.cost %></td>
    <td><%= unit.attack %></td>
    <td><%= unit.defense %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

waarbot/app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

waarbot/app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @unit.code %>
</p>

<p>
  <b>Name:</b>
  <%= @unit.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @unit.cost %>
</p>

<p>
  <b>Attack:</b>
  <%= @unit.attack %>
</p>

<p>
  <b>Defense:</b>
  <%= @unit.defense %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>