waarbot/config/routes.rb
Waarbot::Application.routes.draw do
  resources :targets

  resources :players

  resources :units

end

waarbot/app/models/target.rb
class Target < ActiveRecord::Base


validates_uniqueness_of :ingame_id
end

waarbot/app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  # GET /targets
  # GET /targets.xml
  def index
    @targets = Target.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @targets }
    end
  end

  # GET /targets/1
  # GET /targets/1.xml
  def show
    @target = Target.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/new
  # GET /targets/new.xml
  def new
    @target = Target.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/1/edit
  def edit
    @target = Target.find(params[:id])
  end

  # POST /targets
  # POST /targets.xml
  def create
    @target = Target.new(params[:target])

    respond_to do |format|
      if @target.save
        format.html { redirect_to(@target, :notice => 'Target was successfully created.') }
        format.xml  { render :xml => @target, :status => :created, :location => @target }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /targets/1
  # PUT /targets/1.xml
  def update
    @target = Target.find(params[:id])

    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to(@target, :notice => 'Target was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.xml
  def destroy
    @target = Target.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to(targets_url) }
      format.xml  { head :ok }
    end
  end
end

waarbot/app/helpers/targets_helper.rb
module TargetsHelper
end

waarbot/app/views/targets/_form.html.erb
<%= form_for(@target) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ingame_id %><br />
    <%= f.text_field :ingame_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :xp %><br />
    <%= f.text_field :xp %>
  </div>
  <div class="field">
    <%= f.label :gold %><br />
    <%= f.text_field :gold %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :alliance %><br />
    <%= f.text_field :alliance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

waarbot/app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render 'form' %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

waarbot/app/views/targets/index.html.erb
<h1>Listing targets</h1>

<table>
  <tr>
    <th>Ingame</th>
    <th>Name</th>
    <th>Xp</th>
    <th>Gold</th>
    <th>State</th>
    <th>Population</th>
    <th>Alliance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @targets.each do |target| %>
  <tr>
    <td><%= target.ingame_id %></td>
    <td><%= target.name %></td>
    <td><%= target.xp %></td>
    <td><%= target.gold %></td>
    <td><%= target.state %></td>
    <td><%= target.population %></td>
    <td><%= target.alliance %></td>
    <td><%= link_to 'Show', target %></td>
    <td><%= link_to 'Edit', edit_target_path(target) %></td>
    <td><%= link_to 'Destroy', target, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Target', new_target_path %>

waarbot/app/views/targets/new.html.erb
<h1>New target</h1>

<%= render 'form' %>

<%= link_to 'Back', targets_path %>

waarbot/app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ingame:</b>
  <%= @target.ingame_id %>
</p>

<p>
  <b>Name:</b>
  <%= @target.name %>
</p>

<p>
  <b>Xp:</b>
  <%= @target.xp %>
</p>

<p>
  <b>Gold:</b>
  <%= @target.gold %>
</p>

<p>
  <b>State:</b>
  <%= @target.state %>
</p>

<p>
  <b>Population:</b>
  <%= @target.population %>
</p>

<p>
  <b>Alliance:</b>
  <%= @target.alliance %>
</p>


<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>